### ISSUE TITLE
Login Form Not Submitting 

### ISSUE THREAD

**Issue by cahuizar** [CS450-ECE461/fall2016-group1-userportal#9]
There seems to be an issue with the login form as it does not redirect to user dashboard page when it gets submitted.

Edit: Mongo  was not running.

**Comment by jsatterw** [comment]
After reviewing the code, I believe that this issue may be caused by there being no link to the view "user.pug" in the router files. I've created a branch named "Issue-#9-Fix-WIP" that features changes to the router files that should now include the dashboard view. Currently untested due to setup issues, so the branch is a work in progress, and as such I suggest leaving the issue open.

**Comment by cahuizar** [comment]
Issue has been addressed.
